@echo off
echo Downloading CSV file...
python src/download_csv.py
echo Running API to CSV script...
python src/api2csv.py
echo Running CSV to Database script...
python src/csv2db.py
echo All scripts have been executed.
pause
